require("dotenv").config();

module.exports = {
  users: [
    {
      id: "0",
      username: "admin",
      password: process.env.DEFAULT_ADMIN_PASS,
      firstname: "Admin",
      lastname: "Default",
      email: "vrg.realhome@gmail.com",
      avatar_url: null,
      favorites: null,
      wishlist: null,
      role: "admin",
    },
    {
      id: "1",
      username: "agent",
      password: process.env.DEFAULT_AGENT_PASS,
      firstname: "Agent",
      lastname: "Default",
      email: null,
      avatar_url: null,
      favorites: null,
      wishlist: null,
      role: "agent",
    },
    {
      id: "2",
      username: "user",
      password: process.env.DEFAULT_USER_PASS,
      firstname: "User",
      lastname: "Default",
      email: null,
      avatar_url: null,
      favorites: null,
      wishlist: null,
      role: "user",
    },
  ],
  properties: [
    {
      id: "0",
      agent_id: "1",
      title: "New Apartment Nice View",
      description:
        "Beautiful Huge 1 Family House In Heart Of Westbury. Newly Renovated With New Wood",
      listing_type: "rent",
      price: 638000,
      bedrooms: 3,
      bathrooms: 2,
      address: "Gleemoor Rd, Gleemoor, Cape Town, 7764, South Africa",
      banner_url: null,
      images: null,
      featured: true,
      delisted: false,
    },
    {
      id: "1",
      agent_id: "1",
      title: "Modern Apartments",
      description:
        "Beautiful Huge 1 Family House In Heart Of Westbury. Newly Renovated With New Wood",
      listing_type: "sell",
      price: 638000,
      bedrooms: 3,
      bathrooms: 2,
      address: "14267 Simanga St, Bloekombos, Cape Town, 7570, South Africa",
      banner_url: null,
      images: null,
      featured: true,
      delisted: false,
    },
    {
      id: "2",
      agent_id: "1",
      title: "Comfortable Apartment",
      description:
        "Beautiful Huge 1 Family House In Heart Of Westbury. Newly Renovated With New Wood",
      listing_type: "rent",
      price: 638000,
      bedrooms: 3,
      bathrooms: 2,
      address:
        "140 Bree St, Cape Town City Centre, Cape Town, 8000, South Africa",
      banner_url: null,
      images: null,
      featured: true,
      delisted: false,
    },
    {
      id: "3",
      agent_id: "1",
      title: "Luxury Villa",
      description:
        "Beautiful Huge 1 Family House In Heart Of Westbury. Newly Renovated With New Wood",
      listing_type: "sell",
      price: 638000,
      bedrooms: 3,
      bathrooms: 2,
      address: "2451 Duxbury Rd, Bergvliet, Cape Town, 7945, South Africa",
      banner_url: null,
      images: null,
      featured: true,
      delisted: false,
    },
  ],
};
